import { supabase } from './config'
export { getPublicCatalogue, listActiveCatalogue } from './catalogue'
import type { Product, QuestionnaireSession, ResearchResponse, Seller } from '../types'
const client = () => { if (!supabase) throw new Error('Supabase haijaunganishwa. Weka VITE_SUPABASE_URL na VITE_SUPABASE_PUBLISHABLE_KEY kwenye .env.'); return supabase }
const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message) }
export async function listSellers() { const {data,error}=await client().from('sellers').select('*').order('created_at',{ascending:false});fail(error);return (data??[]).map(row=>({id:row.id,shopName:row.shop_name,sellerName:row.seller_name,phone:row.phone,location:row.location,businessType:row.business_type,createdAt:row.created_at} as Seller)) }
export async function listProducts() { const {data,error}=await client().from('products').select('*').order('created_at',{ascending:false});fail(error);return (data??[]).map(row=>({id:row.id,name:row.name,category:row.category,phoneModel:row.phone_model??'',notes:row.notes??'',normalizedName:row.normalized_name,createdAt:row.created_at} as Product)) }
export async function listResponses() { const {data,error}=await client().from('research_responses').select('*').order('created_at',{ascending:false});fail(error);return (data??[]).map(row=>({id:row.id,sellerId:row.seller_id,productId:row.product_id,buyingPrice:Number(row.buying_price),sellingPrice:Number(row.selling_price),monthlyQuantity:Number(row.monthly_quantity),availability:row.availability,interestedInSupplier:row.interested_in_supplier,initialQuantity:row.initial_quantity??undefined,notes:row.notes??'',createdAt:row.created_at} as ResearchResponse)) }
export async function createSeller(data: Omit<Seller,'id'|'createdAt'>) { const {data:row,error}=await client().from('sellers').insert({shop_name:data.shopName,seller_name:data.sellerName,phone:data.phone,location:data.location,business_type:data.businessType}).select('id').single();fail(error);return row!.id }
export async function createProduct(data: Omit<Product,'id'|'createdAt'|'normalizedName'>) { const normalizedName=data.name.trim().toLocaleLowerCase();const {data:exists,error:check}=await client().from('products').select('id').eq('normalized_name',normalizedName).maybeSingle();fail(check);if(exists)throw new Error('Bidhaa yenye jina hili tayari ipo.');const {data:row,error}=await client().from('products').insert({name:data.name,category:data.category,phone_model:data.phoneModel,notes:data.notes,normalized_name:normalizedName}).select('id').single();fail(error);return row!.id }
export async function saveResponse(data: Omit<ResearchResponse,'id'|'createdAt'>) { const {data:row,error}=await client().from('research_responses').insert({seller_id:data.sellerId,product_id:data.productId,buying_price:data.buyingPrice,selling_price:data.sellingPrice,monthly_quantity:data.monthlyQuantity,availability:data.availability,interested_in_supplier:data.interestedInSupplier,initial_quantity:data.initialQuantity??null,notes:data.notes??''}).select('id').single();fail(error);return row!.id }
export async function createQuestionnaire(productIds:string[], productSnapshots:QuestionnaireSession['productSnapshots']) { const {data,error}=await client().from('questionnaire_sessions').insert({product_ids:productIds,product_snapshots:productSnapshots,active:true}).select('id').single();fail(error);return data!.id }
export async function getSession(token:string) { const {data,error}=await client().rpc('get_public_questionnaire',{p_token:token}); if(error)return null; return data as QuestionnaireSession|null }
export async function publicSaveSeller(token:string, sellerId:string, data:Omit<Seller,'id'|'createdAt'>) { const {error}=await client().rpc('submit_public_seller',{p_token:token,p_seller_id:sellerId,p_shop_name:data.shopName,p_seller_name:data.sellerName,p_phone:data.phone,p_location:data.location,p_business_type:data.businessType});fail(error) }
export async function publicSaveResponse(token:string,responseId:string,data:Omit<ResearchResponse,'id'|'createdAt'>) { const {error}=await client().rpc('submit_public_response',{p_token:token,p_response_id:responseId,p_seller_id:data.sellerId,p_product_id:data.productId,p_buying_price:data.buyingPrice,p_selling_price:data.sellingPrice,p_monthly_quantity:data.monthlyQuantity,p_availability:data.availability,p_interested:data.interestedInSupplier,p_initial_quantity:data.initialQuantity??null,p_notes:data.notes??''});fail(error) }
export async function publicSaveCatalogueResponse(token:string,responseId:string,data:Omit<ResearchResponse,'id'|'createdAt'> & {productModelId?:string}) { const {error}=await client().rpc('submit_public_catalogue_response',{p_token:token,p_response_id:responseId,p_seller_id:data.sellerId,p_product_id:data.productId,p_product_model_id:data.productModelId??null,p_buying_price:data.buyingPrice,p_selling_price:data.sellingPrice,p_monthly_quantity:data.monthlyQuantity,p_availability:data.availability,p_interested:data.interestedInSupplier,p_initial_quantity:data.initialQuantity??null,p_notes:data.notes??''});fail(error) }
