import { useEffect, useMemo, useState } from 'react'
import { Button, Input, Select, Loading } from './UI'
import type { Availability, Seller } from '../types'
import { getPublicCatalogue, publicSaveCatalogueResponse, publicSaveSeller } from '../supabase/database'
import type { CatalogueProduct } from '../supabase/catalogue'

export function SellerCatalogueQuestionnaire({ token }: { token: string }) {
  const [catalogue, setCatalogue] = useState<CatalogueProduct[] | null>(null)
  const [seller, setSeller] = useState({ shopName:'', sellerName:'', phone:'', location:'Bukoba', businessType:'Phone Accessories' })
  const [sellerId, setSellerId] = useState('')
  const [category, setCategory] = useState('')
  const [productId, setProductId] = useState('')
  const [modelId, setModelId] = useState('')
  const [answer, setAnswer] = useState({ buyingPrice:'', sellingPrice:'', monthlyQuantity:'', availability:'available' as Availability, interestedInSupplier:false, initialQuantity:'', notes:'' })
  const [saved, setSaved] = useState(0); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { getPublicCatalogue(token).then(setCatalogue).catch(() => setCatalogue([])) }, [token])
  const categories = useMemo(() => [...new Set((catalogue ?? []).map(p => p.category))], [catalogue])
  const products = (catalogue ?? []).filter(p => p.category === category)
  const product = (catalogue ?? []).find(p => p.id === productId)
  const submitSeller = async (e: React.FormEvent) => { e.preventDefault(); try { setSaving(true); const id=crypto.randomUUID(); await publicSaveSeller(token,id,seller); setSellerId(id) } catch { setError('Imeshindikana kuhifadhi taarifa za duka.') } finally { setSaving(false) } }
  const submitAnswer = async (e: React.FormEvent) => { e.preventDefault(); if (product?.models.length && !modelId) return setError('Chagua brand na model.'); try { setSaving(true); await publicSaveCatalogueResponse(token,crypto.randomUUID(),{sellerId,productId,productModelId:modelId||undefined,buyingPrice:Number(answer.buyingPrice),sellingPrice:Number(answer.sellingPrice),monthlyQuantity:Number(answer.monthlyQuantity),availability:answer.availability,interestedInSupplier:answer.interestedInSupplier,initialQuantity:answer.interestedInSupplier?Number(answer.initialQuantity):undefined,notes:answer.notes}); setSaved(x=>x+1); setCategory('');setProductId('');setModelId('');setAnswer({buyingPrice:'',sellingPrice:'',monthlyQuantity:'',availability:'available',interestedInSupplier:false,initialQuantity:'',notes:''});setError('') } catch { setError('Imeshindikana kuhifadhi bidhaa. Jaribu tena.') } finally { setSaving(false) } }
  if (catalogue === null) return <div className="public"><Loading/></div>
  if (!catalogue.length) return <div className="public"><div className="question"><h1>Kiungo hiki si halali</h1></div></div>
  if (!sellerId) return <div className="public"><form className="question" onSubmit={submitSeller}><div className="public-brand">KAGERA ACCESS</div><h1>Taarifa za duka</h1><p>Chagua bidhaa zilizopo dukani kwako tu. Huna haja ya kujaza zote.</p><Input label="Jina la Duka" required value={seller.shopName} onChange={e=>setSeller({...seller,shopName:e.target.value})}/><Input label="Jina la Mfanyabiashara" required value={seller.sellerName} onChange={e=>setSeller({...seller,sellerName:e.target.value})}/><Input label="Eneo" required value={seller.location} onChange={e=>setSeller({...seller,location:e.target.value})}/><Input label="Namba ya WhatsApp" required value={seller.phone} onChange={e=>setSeller({...seller,phone:e.target.value})}/><Select label="Aina ya Biashara" value={seller.businessType} onChange={e=>setSeller({...seller,businessType:e.target.value})}><option>Phone Accessories</option><option>Phone Shop</option><option>Phone Technician</option></Select>{error&&<p className="error">{error}</p>}<Button disabled={saving}>{saving?'Inahifadhi…':'Endelea'}</Button></form></div>
  return <div className="public"><form className="question" onSubmit={submitAnswer}><div className="public-brand">KAGERA ACCESS</div><h1>Bidhaa zilizopo dukani</h1><p>Ongeza bidhaa moja baada ya nyingine. Ukimaliza, bonyeza Maliza.</p><Select label="Category" required value={category} onChange={e=>{setCategory(e.target.value);setProductId('');setModelId('')}}><option value="">Chagua category</option>{categories.map(x=><option key={x}>{x}</option>)}</Select><Select label="Bidhaa" required disabled={!category} value={productId} onChange={e=>{setProductId(e.target.value);setModelId('')}}><option value="">Chagua bidhaa</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select>{product?.models.length ? <Select label="Brand na Phone Model" required value={modelId} onChange={e=>setModelId(e.target.value)}><option value="">Chagua model</option>{product.models.map(m=><option key={m.id} value={m.id}>{m.brand} — {m.model}</option>)}</Select> : product ? <p className="notice">Generic / N/A</p> : null}<Input label="Bei unayonunua (TZS)" type="number" min="0" required value={answer.buyingPrice} onChange={e=>setAnswer({...answer,buyingPrice:e.target.value})}/><Input label="Bei unayouza (TZS)" type="number" min="0" required value={answer.sellingPrice} onChange={e=>setAnswer({...answer,sellingPrice:e.target.value})}/><Input label="Kiasi kinachouzwa kwa mwezi" type="number" min="1" required value={answer.monthlyQuantity} onChange={e=>setAnswer({...answer,monthlyQuantity:e.target.value})}/><Select label="Upatikanaji" value={answer.availability} onChange={e=>setAnswer({...answer,availability:e.target.value as Availability})}><option value="available">Inapatikana</option><option value="sometimes">Wakati mwingine hukosekana</option><option value="often">Mara nyingi hukosekana</option></Select><label className="check"><input type="checkbox" checked={answer.interestedInSupplier} onChange={e=>setAnswer({...answer,interestedInSupplier:e.target.checked})}/> Anahitaji supplier mpya</label>{answer.interestedInSupplier&&<Input label="Kiasi cha awali" type="number" min="1" required value={answer.initialQuantity} onChange={e=>setAnswer({...answer,initialQuantity:e.target.value})}/>}<Input label="Maelezo (si lazima)" value={answer.notes} onChange={e=>setAnswer({...answer,notes:e.target.value})}/>{error&&<p className="error">{error}</p>}<Button disabled={saving}>{saving?'Inahifadhi…':'Hifadhi bidhaa hii'}</Button><Button type="button" className="secondary" onClick={()=>setSaved(-1)}>Maliza ({saved} bidhaa)</Button>{saved<0&&<div className="thanks"><h1>Asante!</h1><p>Taarifa zako zimepokelewa.</p></div>}</form></div>
}
